import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Welcome to my website CSE 223!
          </p>
          <div>
            <a
              href="https://www.instagram.com/allart.drawings/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/assets/EP Logo.png"
                //alt="Vercel Logo"
                //className={styles.vercelLogo}
                width={85}
                height={85}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <p>
            Hi, my name is <span style={{ color: 'maroon'}}>Erick </span>
            <span style = {{display: 'block' }}></span>Currently a Junior at Washington State University
          </p>
        </div>

        <div>
          <p>
            This is my first website, and is still a work in progress. Below I have some links to help introduce myself.
          </p>
        </div>

        <div className={styles.grid}>
          <a
            href="https://www.linkedin.com/in/erick-pairault-17252b264/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              About Me <span>-&gt;</span>
            </h2>
            <p>
              Visit my Linked-In page to get connected with me and see more about me.
            </p>
          </a>

          <a
            href="https://github.com/Erick-Pairault"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Projects <span>-&gt;</span>
            </h2>
            <p>
              Check out my GitHub to see some of my projects.
            </p>
          </a>

          <a
            href="https://www.youtube.com/@Eric-YT-Tutorials"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Tutorial <span>-&gt;</span>
            </h2>
            <p>
              Check out my YouTube channel where I give a set-by-step on how I got this far!
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
